language: python

python:
- 3.4
- 3.5
- 3.6

install:
- pip install -r requirements-test.txt
- pip install codecov
- pip install -e .

script:
- conda-mirror-ng -h
- pytest --cov conda_mirror_ng
- flake8

after_success:
- codecov
